name = "NGSIM"
uuid = "195157bc-cedd-5875-9ea7-7cfb75f30b3c"
version = "0.0.0"

[deps]
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AutoViz", "NBInclude", "Test"]
